id: P009369
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24618
  title: དྲང་ངེས་རྣམ་འབྱེད་ཀྱི་དཀའ་འགྲེལ་དགོངས་པ་རབ་གསལ།
  author: ''
  volumes:
    2a890c042020452e95b6d986a7e50a9d:
      image_group_id: I1KG24637
      title: ''
      volume_number: 1
      total_pages: 194
