id: IA8934CC2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T04:51:01+00:00'
last_modified: '2022-06-08T10:31:30.883465+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24618
  title: དྲང་ངེས་རྣམ་འབྱེད་ཀྱི་དཀའ་འགྲེལ་དགོངས་པ་རབ་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ED1A:
      image_group_id: I1KG24637
      title: ''
      total_pages: 194
      order: 1
      base_file: ED1A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
